### ISSUE TITLE
Building fails with default instructions on Linux

### ISSUE THREAD

**Issue by mstubenschrott** [matsim-vsp/simwrapper#1]
I tried building simwrapper on Fedora 36 in a WSL2 environment with default instructions given in the README.md.

`npm ci` fails with this error in the log:
```
6947 verbose node v16.14.0
6948 verbose npm  v8.3.1
6949 error code EBADPLATFORM
6950 error notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
6951 error notsup Valid OS:    darwin
6951 error notsup Valid Arch:  undefined
6951 error notsup Actual OS:   linux
6951 error notsup Actual Arch: x64
```

I tried removing the package-lock.json, also adding `--no-optional` but to no avail.

What finally works was running the same command as in `.github/workflows/autobuild.yml`:

```
npm ci -f --no-optional
```

You might want to update the README.md that using the --force parameter might be currently needed.

**Comment by billyc** [comment]
Moved to

https://github.com/simwrapper/simwrapper/issues/359
