### ISSUE TITLE
Link Plots: Width only scales for positive values, not for negative values

### ISSUE THREAD

**Issue by tschlenther** [matsim-vsp/simwrapper#2]
In the link viz, one can set the link width relative to variable values. However, for difference plots, the link width only scales with positive values, not with negative values. Meaning a link associated with a high positive value is really wide, a link with a stringly negative value is slim...

![grafik](https://github.com/matsim-vsp/simwrapper/assets/13538764/6ff38521-cbd3-4bbf-9d57-c4ba97a892fa)

**Comment by billyc** [comment]
Moved to

https://github.com/simwrapper/simwrapper/issues/358
