### ISSUE TITLE
Sum/Mean Aggregation in "XY hexagons (aggregate)" Plot

### ISSUE THREAD

**Issue by jakobrehmann** [matsim-vsp/simwrapper#3]
As is, aggregation means counting the number of x/y coordinate pairs in each hexagon. The desired feature would be that simwrapper can also take the mean (or sum) of a user-defined value column. Potential use case: calculate the average score per hexagon.

**Comment by billyc** [comment]
Moved to

https://github.com/simwrapper/simwrapper/issues/357
