### ISSUE TITLE
Difference Plot in "XY hexagons (aggregate)"

### ISSUE THREAD

**Issue by jakobrehmann** [matsim-vsp/simwrapper#4]
Including difference plot functionality in the "XY hexagons (aggregate)" plot, meaning: 
1) user specifies base and policy CSV in yaml 
2) simwrapper aggregates both CSVs on same hex grid (ideally using sum/mean methods as requested in Issue #3 )
3) simwrapper calculates & displays the difference for each hexagonal pixel. 

Use case: visualizing score change per hexagonal pixel.

**Comment by billyc** [comment]
Moved to

https://github.com/simwrapper/simwrapper/issues/356
