### ISSUE TITLE
Noise dashboard does not show tooltyp when hovering over immission bars (gridmap)

### ISSUE THREAD

**Issue by simei94** [matsim-vsp/simwrapper#5]
When creating some noise dashboards I saw that there is no tooltip (with a value / id for the bar) when I hover over the different immission bars. The plot in the dashboard is of the type gridmap. I can provide you some example data if needed, but the example data from amtsim-libs should just do fine, I think.
![image](https://github.com/matsim-vsp/simwrapper/assets/67737999/58b26ce4-b88a-491f-907b-307f03cf2714)

**Comment by billyc** [comment]
Moved to

https://github.com/simwrapper/simwrapper/issues/355
